//! Process helpers for launching content.
//!
//! Video plays in libmpv — the same engine Stremio uses — skinned with a
//! remote-first TV OS overlay. We point mpv at a private
//! config dir (MPV_HOME) that tvosd fully provisions from its bundled, editable
//! player (see tvosd/player/): the TV player UI, thumbfast thumbnails, our
//! controller + upscaler scripts, an input map, and a freshly written mpv.conf
//! holding the resolved Enhance shader chain. Because everything travels via
//! MPV_HOME, *any* mpv launch picks it up — including the one webtorrent-cli
//! spawns for torrents — so torrents get the same player, UI, and upscaler too.

use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;
use std::time::{Duration, Instant};

use include_dir::{include_dir, Dir};

use crate::settings::EnhanceMode;
use crate::upscale::Profile;

/// The bundled player (TV overlay + thumbfast + our controller/upscaler scripts and
/// config), embedded so the daemon always provisions a complete, working UI.
static PLAYER_FILES: Dir = include_dir!("$CARGO_MANIFEST_DIR/player");

/// The currently playing player process, if any. Starting a new video stops
/// the previous one so two windows never fight over the screen.
static PLAYER: Mutex<Option<Child>> = Mutex::new(None);

#[derive(Clone, Debug)]
pub struct PlayerMeta {
    pub title: String,
    pub subtitle: Option<String>,
    pub source: Option<String>,
    /// A live stream: the overlay shows a "● LIVE" indicator instead of a
    /// seek bar / duration, and playback never records a resume position.
    pub live: bool,
    /// HTTP headers some IPTV streams require to serve (passed to mpv).
    pub referrer: Option<String>,
    pub user_agent: Option<String>,
}

impl PlayerMeta {
    pub fn new(title: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            subtitle: None,
            source: None,
            live: false,
            referrer: None,
            user_agent: None,
        }
    }

    /// Mark this as a live stream.
    pub fn live(mut self) -> Self {
        self.live = true;
        self
    }
}

/// Base mpv settings for the 10-foot player: fullscreen, good streaming cache,
/// sensible subtitle/audio defaults. The TV overlay and Enhance shaders are
/// appended per-playback.
const BASE_MPV_CONF: &str = "\
# Generated by tvosd on each playback — do not edit.
fullscreen=yes
border=no
terminal=no
force-window=immediate
keep-open=yes
hwdec=auto-safe
profile=high-quality
slang=en,eng
alang=en,eng
sub-auto=fuzzy
sub-font-size=42
# The TV overlay raises subtitles above its controls; keep that out of watch-later state.
watch-later-options-remove=sub-pos
# Roboto everywhere: the shell UI, the TV player overlay, and mpv's own
# OSD/subtitles all use the one system typeface (bundled in
# player/fonts/, so it renders even where Roboto isn't installed system-wide).
osd-font=Roboto
sub-font=Roboto
volume=100
volume-max=130
# Smooth streaming of remote sources.
cache=yes
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=64MiB
demuxer-readahead-secs=30
network-timeout=60
ytdl-format=bestvideo[height<=?2160]+bestaudio/best
";

pub fn play_video(
    target: &str,
    profile: &Profile,
    mode: EnhanceMode,
    hint: &str,
    item_id: Option<&str>,
    track_id: Option<&str>,
    meta: Option<&PlayerMeta>,
) -> Result<(), String> {
    let start = item_id.and_then(crate::resume::position);
    let home = prepare_mpv_home(profile, mode, hint, start, meta, false);
    let mut player = PLAYER.lock().unwrap_or_else(|e| e.into_inner());
    stop(&mut player);

    crate::log_info!("playing [{}] mpv {target}", profile.name);
    let _ = std::fs::remove_file(home.join(".started")); // fresh start signal
    let _ = std::fs::remove_file(home.join(".health"));
    let _ = std::fs::remove_file(home.join("mpv.log"));
    // In the TV/gamescope session, run mpv through gamescope so it lands in the
    // compositor's fullscreen output like everything else; degrades to a direct
    // mpv launch off-session or when gamescope isn't installed.
    let mpv = resolve_mpv();
    let mut cmd = gamescope_command(&mpv);
    cmd.env("MPV_HOME", &home)
        .env("PATH", child_path())
        .args(["--no-terminal", target])
        .stdin(Stdio::null())
        .stdout(crate::logging::child_output())
        .stderr(crate::logging::child_output());
    own_process_group(&mut cmd);
    if let Some(id) = item_id {
        cmd.env("TVOS_POSITION_FILE", crate::resume::position_file(id));
        cmd.env("TVOS_CONTENT_ID", id);
        // resume.lua tags the watched-marker with the *precise* id (an episode
        // carries season:episode) so the Trakt/AniList scrobbler can resolve
        // exactly what was watched; the resume position stays keyed by item_id.
        cmd.env("TVOS_ITEM_ID", track_id.unwrap_or(id));
    }
    let child = cmd
        .spawn()
        .map_err(|e| format!("could not start mpv: {e}"))?;
    confirm_started(&home, child, false, &mut player)
}

/// Opens a link (a WatchHub service, an addon's /configure page) in the
/// system's default handler — the browser, or the streaming service's app.
pub fn open_external(url: &str) -> Result<(), String> {
    let opener = if cfg!(target_os = "macos") {
        "open"
    } else {
        "xdg-open"
    };
    spawn_detached(opener, &[url]).map_err(|e| format!("could not open link: {e}"))
}

/// Streams a torrent magnet in mpv (with the upscaler + UI) via webtorrent-cli's
/// `--mpv` mode, which serves the torrent over local HTTP so seeking works.
pub fn play_torrent(
    magnet: &str,
    file_idx: Option<i64>,
    profile: &Profile,
    mode: EnhanceMode,
    hint: &str,
    item_id: Option<&str>,
    track_id: Option<&str>,
    meta: Option<&PlayerMeta>,
) -> Result<(), String> {
    let webtorrent = resolve_webtorrent().ok_or(
        "Torrent playback needs webtorrent-cli. Install it with `npm install -g webtorrent-cli`, \
         or configure the addon with a debrid service (e.g. RealDebrid) for direct streams.",
    )?;
    let start = item_id.and_then(crate::resume::position);
    let home = prepare_mpv_home(profile, mode, hint, start, meta, true);
    let mut player = PLAYER.lock().unwrap_or_else(|e| e.into_inner());
    stop(&mut player);

    // Download to a predictable, disk-backed cache dir. webtorrent otherwise
    // writes to the working dir or /tmp (often a small tmpfs), which fills up
    // fast on big torrents — a common cause of "no space" failures.
    let cache = torrent_cache();
    let _ = std::fs::create_dir_all(&cache);

    // `webtorrent <magnet> --mpv` (download is the default command). With a
    // file index, --select streams that file; without it webtorrent picks the
    // largest playable file automatically.
    //
    // --keep-seeding is essential: by default webtorrent-cli QUITS as soon as it
    // considers the download "done", which closes the local HTTP server out from
    // under mpv. mpv, mid-read, then aborts with "http: Immediate exit requested"
    // and quits — the exact symptom of "streams don't launch". It bit hardest
    // when partial data was already cached (the file finishes seconds in) or the
    // file was small. Keeping it seeding leaves the server up for the whole
    // playback; webtorrent still exits when mpv itself closes.
    // Give webtorrent its own free port for the local HTTP server. Its default
    // is 8000, and when that's taken — e.g. an earlier --keep-seeding instance
    // orphaned by a daemon restart is still seeding on it — webtorrent-cli's
    // fallback is buggy and it *never launches the player*. That was the real
    // "sometimes the stream doesn't start". A fresh port makes it impossible.
    let port = free_port();
    let mut cmd = Command::new(&webtorrent);
    cmd.arg(magnet)
        .arg("--mpv")
        .arg("--keep-seeding")
        .args(["--port", &port.to_string()])
        // --quiet drops webtorrent's once-a-second full-screen progress redraw,
        // which otherwise floods the shared log file (mpv's own log-file keeps
        // the rich playback diagnostics, and webtorrent still prints errors).
        .arg("--quiet")
        .arg("--out")
        .arg(&cache);
    if let Some(i) = file_idx {
        cmd.args(["--select", &i.to_string()]);
    }
    // webtorrent spawns mpv; MPV_HOME makes that mpv use our UI + shaders.
    // Both webtorrent's and mpv's output go to the persistent log so a failed
    // torrent (no peers, no space, missing mpv) leaves a visible reason — the
    // old code discarded webtorrent's stdout entirely, which is exactly why
    // failures looked like "nothing happened".
    crate::log_info!(
        "playing [torrent {}] via {webtorrent}: {} file_idx={:?} port={} cache={}",
        profile.name,
        magnet_summary(magnet),
        file_idx,
        port,
        cache.display()
    );
    let _ = std::fs::remove_file(home.join(".started")); // fresh start signal
    let _ = std::fs::remove_file(home.join(".health"));
    let _ = std::fs::remove_file(home.join("mpv.log"));
    cmd.env("MPV_HOME", &home)
        .env("PATH", torrent_child_path(&home))
        .stdin(Stdio::null())
        .stdout(crate::logging::child_output())
        .stderr(crate::logging::child_output());
    own_process_group(&mut cmd);
    if let Some(id) = item_id {
        // webtorrent's mpv inherits these, so resume.lua can save the position
        // and write the watched-marker — torrents scrobble just like direct
        // streams (previously the marker was never written for torrents).
        cmd.env("TVOS_POSITION_FILE", crate::resume::position_file(id));
        cmd.env("TVOS_CONTENT_ID", id);
        cmd.env("TVOS_ITEM_ID", track_id.unwrap_or(id));
    }
    cmd.env("TVOS_TORRENT_PLAYBACK", "1");
    let child = cmd
        .spawn()
        .map_err(|e| format!("could not start torrent stream: {e}"))?;
    confirm_started(&home, child, true, &mut player)
}

/// Waits until playback actually starts before reporting success, so the shell
/// shows a real error instead of a window that never appears. The signal is the
/// `.started` marker that scripts/startup.lua writes on mpv's `file-loaded`
/// event (reliable even for torrents, where webtorrent runs mpv with
/// --really-quiet and the log file is suppressed). As a fast path we also watch
/// mpv's log for an open failure (present for direct streams). On failure (the
/// player exits, the source can't be opened, or nothing starts in time) the
/// just-spawned process is killed and a clear message is returned.
fn confirm_started(
    home: &Path,
    mut child: Child,
    torrent: bool,
    player: &mut Option<Child>,
) -> Result<(), String> {
    let started = home.join(".started");
    let log = home.join("mpv.log");
    // Torrent startup can legitimately take a while: webtorrent has to join
    // swarms, choose a file, start a local HTTP server, and only then launch
    // mpv. Returning after 25s caused the UI to show an error while the player
    // appeared moments later. Direct HTTP failures are still kept quick.
    let timeout = Duration::from_secs(if torrent { 90 } else { 15 });
    let deadline = Instant::now() + timeout;

    let outcome = loop {
        std::thread::sleep(Duration::from_millis(400));

        if started.exists() {
            break Ok(());
        }

        if let Ok(text) = std::fs::read_to_string(&log) {
            if text.contains("Failed to open")
                || text.contains("Opening failed or was aborted")
                || text.contains("Failed to recognize file format")
            {
                break Err(if torrent {
                    "Could not open this torrent's file — the source looks broken or not enough data arrived. Try another source."
                } else {
                    "Could not open the stream — the source may be down. Try another source."
                });
            }
        }

        if matches!(child.try_wait(), Ok(Some(_))) {
            break Err(if torrent {
                "The torrent stream stopped before it started — likely no seeders or an unavailable source. Try another source."
            } else {
                "The player exited before the stream started — the source may be unavailable. Try another source."
            });
        }

        if Instant::now() >= deadline {
            break Err(if torrent {
                "Torrent stream did not start in time. Pick a smaller/better-seeded quality, or use a debrid service for instant streams."
            } else {
                "Stream didn't start in time — the source may be slow or unavailable. Try another source."
            });
        }
    };

    match outcome {
        Ok(()) => {
            *player = Some(child);
            Ok(())
        }
        Err(message) => {
            kill_tree(&mut child);
            crate::log_error!("{message}");
            Err(message.to_string())
        }
    }
}

/// Puts the child in its own process group so [`kill_tree`] can take out the
/// whole tree. Matters for torrents: the tracked child is webtorrent, and the
/// mpv *it* spawns must die with it — otherwise switching content leaves an
/// orphaned player window fighting the new one for the screen.
fn own_process_group(cmd: &mut Command) {
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        cmd.process_group(0);
    }
}

/// Kills the child and every process in its group (mpv under webtorrent, etc.).
/// SIGTERM the group first for a clean shutdown, then — after a short grace
/// period — SIGKILL anything still alive so a wedged player can never survive.
fn kill_tree(child: &mut Child) {
    #[cfg(unix)]
    {
        let pgid = format!("-{}", child.id());
        let signal = |sig: &str| {
            let _ = Command::new("kill")
                .args([sig, "--", &pgid])
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .status();
        };
        signal("-TERM");
        // Give the group a moment to exit gracefully; if the tracked child is
        // still running, escalate to SIGKILL on the whole group.
        let deadline = Instant::now() + Duration::from_millis(1500);
        loop {
            match child.try_wait() {
                Ok(Some(_)) => break,
                _ if Instant::now() >= deadline => {
                    signal("-KILL");
                    break;
                }
                _ => std::thread::sleep(Duration::from_millis(100)),
            }
        }
    }
    let _ = child.kill();
    let _ = child.wait();
}

/// Sets up MPV_HOME for this playback and returns it: provisions the bundled
/// player, writes mpv.conf with the resolved shader chain, and writes the
/// upscaler menu's preset list. Idempotent.
fn prepare_mpv_home(
    profile: &Profile,
    mode: EnhanceMode,
    hint: &str,
    start: Option<f64>,
    meta: Option<&PlayerMeta>,
    torrent: bool,
) -> PathBuf {
    let home = mpv_home();
    provision_player(&home);
    write_mpv_wrapper(&home);
    write_mpv_conf(&home, profile, start, meta, torrent);
    write_upscalers(&home, mode, hint);
    write_player_meta(&home, meta);
    home
}

/// Player bundle version. Bump it to ship new defaults: on the next launch the
/// bundled files are rewritten *once*. Otherwise the daemon never touches them
/// again, so anything you edit under MPV_HOME stays edited (no rebuild needed),
/// and deleting a file restores its shipped default on the next launch.
const PLAYER_VERSION: &str = "16";

/// Installs the bundled player into MPV_HOME so the TV overlay is always the UI.
/// The entire player tree (TV overlay, thumbfast, our scripts and config) is
/// extracted. Each file is (re)written only when missing or when
/// PLAYER_VERSION changes, which makes MPV_HOME the live, editable surface: edit
/// input.conf or scripts/*.lua there and they take effect on the next play;
/// delete one to restore its shipped default.
fn provision_player(home: &Path) {
    let _ = std::fs::create_dir_all(home);
    let stamp = home.join(".player-version");
    let refresh = std::fs::read_to_string(&stamp).unwrap_or_default().trim() != PLAYER_VERSION;

    extract_dir(&PLAYER_FILES, home, refresh);

    // A user override that we create once and then never touch — put personal
    // mpv tweaks here; the generated mpv.conf includes it last so they win.
    let user_conf = home.join("user.conf");
    if !user_conf.exists() {
        let _ = std::fs::write(
            &user_conf,
            "# TV OS — your personal mpv overrides. Never overwritten by tvosd.\n\
             # Anything here wins over the generated mpv.conf. e.g.:\n\
             #   osd-font=Roboto\n#   volume=80\n",
        );
    }

    if refresh {
        // Remove players/scripts shipped by earlier versions so MPV_HOME doesn't
        // load old bundled OSCs alongside the TV overlay.
        let _ = std::fs::remove_dir_all(home.join("scripts/uosc"));
        let _ = std::fs::remove_file(home.join("fonts/uosc_icons.otf"));
        let _ = std::fs::remove_file(home.join("fonts/uosc_textures.ttf"));
        let _ = std::fs::remove_file(home.join("script-opts/uosc.conf"));
        let _ = std::fs::remove_file(home.join("scripts/enhance-toggle.lua"));
        let _ = std::fs::remove_file(home.join("enhance-toggle.lua"));
        // Legacy ModernZ OSC — superseded by tvos_player.lua; remove so an old
        // install doesn't keep a stale, unused theme (and its font) around.
        let _ = std::fs::remove_file(home.join("scripts/modernz.lua"));
        let _ = std::fs::remove_file(home.join("script-opts/modernz.conf"));
        let _ = std::fs::remove_file(home.join("fonts/modernz-icons.ttf"));
        let _ = std::fs::remove_file(home.join(".uosc-version")); // old stamp name
        let _ = std::fs::write(&stamp, PLAYER_VERSION);
    }
}

/// Recursively writes an embedded dir under `dest`, creating parents. A file is
/// written when `refresh` is set or it doesn't exist yet (so user edits stick).
fn extract_dir(dir: &Dir, dest: &Path, refresh: bool) {
    for file in dir.files() {
        let path = dest.join(file.path());
        if refresh || !path.exists() {
            if let Some(parent) = path.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let _ = std::fs::write(&path, file.contents());
        }
    }
    for sub in dir.dirs() {
        extract_dir(sub, dest, refresh);
    }
}

/// Writes the per-playback mpv.conf: base 10-foot settings, the TV overlay,
/// gamepad input on, a real log file, and the resolved Enhance shader chain.
fn write_mpv_conf(
    home: &Path,
    profile: &Profile,
    start: Option<f64>,
    meta: Option<&PlayerMeta>,
    torrent: bool,
) {
    let mut conf = String::from(BASE_MPV_CONF);
    if torrent {
        conf.push_str(
            "\
# Torrent playback needs a larger reservoir than ordinary HTTP streams. Start
# and rebuffer more deeply on underrun without delaying launch acknowledgement.
cache-pause=yes
cache-pause-wait=8
cache-secs=180
demuxer-max-bytes=768MiB
demuxer-max-back-bytes=128MiB
demuxer-readahead-secs=90
stream-buffer-size=4MiB
",
        );
    }
    conf.push_str("osc=no\n"); // TV OS draws its own remote-first overlay
    conf.push_str("osd-bar=no\n");
    conf.push_str("load-scripts=no\n");
    let scripts = [
        "startup.lua",
        "resume.lua",
        "skip.lua",
        "upscaler.lua",
        "controller.lua",
        "thumbfast.lua", // scrubber thumbnail previews for tvos_player
        "tvos_player.lua",
    ]
    .map(|script| format!("~~/scripts/{script}"))
    .join(":");
    if let Some(line) = conf_line("scripts", Some(&scripts)) {
        conf.push_str(&line);
    }
    conf.push_str("input-gamepad=yes\n"); // controller.lua maps the buttons
                                          // Resume where we left off (works for torrents too, since their mpv only
                                          // reads this config — we can't pass it args).
    if let Some(secs) = start {
        conf.push_str(&format!("start={secs}\n"));
    }
    if let Some(meta) = meta {
        let title = conf_safe_value(&meta.title);
        if let Some(line) = conf_line("force-media-title", Some(&title)) {
            conf.push_str(&line);
        }
        // Some IPTV streams 403 without the referrer / user-agent their
        // playlist specifies — pass them straight through to mpv.
        if let Some(referrer) = meta.referrer.as_deref() {
            if let Some(line) = conf_line("referrer", Some(&conf_safe_value(referrer))) {
                conf.push_str(&line);
            }
        }
        if let Some(ua) = meta.user_agent.as_deref() {
            if let Some(line) = conf_line("user-agent", Some(&conf_safe_value(ua))) {
                conf.push_str(&line);
            }
        }
    }
    // A real log file (mpv writes nothing to a suppressed terminal) so the
    // actual reason a stream fails is always visible.
    if let Some(line) = conf_line("log-file", Some(&home.join("mpv.log").to_string_lossy())) {
        conf.push_str(&line);
    }
    // Turn the resolved profile's mpv flags into config lines so they apply to
    // webtorrent's mpv too (which we can't pass args to). Handle both
    // "--key=value" and valueless "--flag" forms; skip anything unparseable or
    // carrying characters that would break out of the quoted config value.
    for arg in &profile.args {
        let body = arg.trim_start_matches("--");
        let (key, value) = match body.split_once('=') {
            Some((k, v)) => (k, Some(v)),
            None => (body, None),
        };
        match conf_line(key, value) {
            Some(line) => conf.push_str(&line),
            None => crate::log_warn!("mpv.conf: dropping unparseable profile arg {arg:?}"),
        }
    }
    // User overrides win — included last so they override anything above.
    if let Some(line) = conf_line("include", Some(&home.join("user.conf").to_string_lossy())) {
        conf.push_str(&line);
    }
    let _ = std::fs::write(home.join("mpv.conf"), conf);
}

fn write_player_meta(home: &Path, meta: Option<&PlayerMeta>) {
    let path = home.join("player-meta.json");
    let Some(meta) = meta else {
        let _ = std::fs::remove_file(path);
        return;
    };
    let json = serde_json::json!({
        "title": meta.title,
        "subtitle": meta.subtitle,
        "source": meta.source,
        "live": meta.live,
    });
    let _ = std::fs::write(path, json.to_string());
}

/// webtorrent-cli hardcodes the player command as plain `mpv`. Put a tiny
/// wrapper in MPV_HOME/bin and prepend that directory to PATH for torrent
/// launches so webtorrent's child mpv definitely uses our config/scripts and
/// writes the `.started` marker. This avoids depending on environment handling
/// inside webtorrent's shell-based spawn.
fn write_mpv_wrapper(home: &Path) {
    let bin = home.join("bin");
    let _ = std::fs::create_dir_all(&bin);
    let real_mpv = resolve_mpv_absolute();
    let script = format!(
        "#!/usr/bin/env sh\n\
         export MPV_HOME={home}\n\
         exec {mpv} --config-dir={home} \"$@\"\n",
        home = shell_quote(&home.to_string_lossy()),
        mpv = shell_quote(&real_mpv),
    );
    let path = bin.join("mpv");
    let _ = std::fs::write(&path, script);
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755));
    }
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn magnet_summary(magnet: &str) -> String {
    let hash = magnet
        .split('&')
        .find_map(|part| {
            part.strip_prefix("magnet:?xt=urn:btih:")
                .or_else(|| part.strip_prefix("xt=urn:btih:"))
        })
        .unwrap_or("unknown");
    let dn = magnet
        .split('&')
        .find_map(|part| part.strip_prefix("dn="))
        .unwrap_or("torrent");
    let trackers = magnet.matches("&tr=").count();
    format!("btih={hash} dn={dn} trackers={trackers}")
}

/// One validated `key` / `key="value"` config line, or None if the key or value
/// is unsafe. mpv reads config values as double-quoted strings with no escape
/// mechanism, so a `"` or newline in a value (e.g. a shader path crafted to
/// inject settings) would break out of the value — reject those outright. A
/// valueless flag becomes a bare `key` line (equivalent to `key=yes`).
fn conf_line(key: &str, value: Option<&str>) -> Option<String> {
    let key = key.trim();
    if key.is_empty()
        || !key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return None;
    }
    match value {
        None => Some(format!("{key}\n")),
        Some(v) if v.contains('"') || v.contains('\n') || v.contains('\r') => None,
        Some(v) => Some(format!("{key}=\"{v}\"\n")),
    }
}

fn conf_safe_value(value: &str) -> String {
    value
        .replace(['"', '\n', '\r'].as_ref(), " ")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

/// Writes the preset list the in-player upscaler menu reads, marking the one the
/// resolver chose as active. Switching between them is live (no reload).
fn write_upscalers(home: &Path, mode: EnhanceMode, hint: &str) {
    let presets = crate::upscale::presets();
    let mut active = crate::upscale::active_preset(mode, hint);
    if !presets.iter().any(|p| p.name == active) {
        active = "Off".to_string();
    }
    let json = serde_json::json!({
        "active": active,
        "presets": presets
            .iter()
            .map(|p| serde_json::json!({ "name": p.name, "hint": p.hint, "shaders": p.shaders }))
            .collect::<Vec<_>>(),
    });
    let _ = std::fs::write(home.join("upscalers.json"), json.to_string());
}

/// An absolute home directory. Falls back to `/root` rather than collapsing to
/// a relative path (which would scatter tvos data across whatever cwd the
/// daemon happened to start in) when HOME is unset.
fn home_dir() -> PathBuf {
    match std::env::var("HOME") {
        Ok(h) if !h.is_empty() => PathBuf::from(h),
        _ => PathBuf::from("/root"),
    }
}

fn mpv_home() -> PathBuf {
    if let Ok(dir) = std::env::var("TVOS_MPV_HOME") {
        return PathBuf::from(dir);
    }
    crate::settings::profile_dir().join("mpv")
}

/// Where webtorrent downloads torrent data (disk-backed, easy to clear).
fn torrent_cache() -> PathBuf {
    if let Ok(dir) = std::env::var("TVOS_TORRENT_DIR") {
        return PathBuf::from(dir);
    }
    crate::settings::profile_dir().join("torrents")
}

/// An OS-assigned free TCP port (bound to :0, then released) for webtorrent's
/// HTTP server, so it never collides with a stray seeder on the default 8000.
fn free_port() -> u16 {
    std::net::TcpListener::bind("127.0.0.1:0")
        .ok()
        .and_then(|l| l.local_addr().ok())
        .map(|a| a.port())
        .unwrap_or(8000)
}

/// Finds the webtorrent binary on PATH, or in the usual npm-global locations
/// (a desktop-launched daemon often has a minimal PATH that misses them).
fn resolve_webtorrent() -> Option<String> {
    if command_exists("webtorrent") {
        return Some("webtorrent".to_string());
    }
    let home = home_dir().to_string_lossy().into_owned();
    let profile = crate::settings::profile_dir()
        .to_string_lossy()
        .into_owned();
    let mut candidates = vec![
        format!("{profile}/node_modules/.bin/webtorrent"),
        format!("{home}/.npm-global/bin/webtorrent"),
        format!("{home}/.local/bin/webtorrent"),
        format!("{home}/node_modules/.bin/webtorrent"),
        "/opt/homebrew/bin/webtorrent".to_string(),
        "/usr/local/bin/webtorrent".to_string(),
        "/usr/bin/webtorrent".to_string(),
    ];
    // `npm prefix -g`/bin is where `npm install -g` puts binaries.
    if let Ok(out) = Command::new("npm").args(["prefix", "-g"]).output() {
        if out.status.success() {
            let prefix = String::from_utf8_lossy(&out.stdout).trim().to_string();
            candidates.push(format!("{prefix}/bin/webtorrent"));
        }
    }
    candidates
        .into_iter()
        .find(|p| std::path::Path::new(p).exists())
}

fn resolve_mpv() -> String {
    for var in ["TVOS_MPV", "TVOS_VIDEO_PLAYER"] {
        if let Ok(player) = std::env::var(var) {
            let player = player.trim();
            if !player.is_empty() {
                if std::path::Path::new(player).is_absolute() {
                    if std::path::Path::new(player).exists() {
                        return player.to_string();
                    }
                } else if command_exists(player) {
                    return player.to_string();
                }
            }
        }
    }
    if command_exists("mpv") {
        return "mpv".to_string();
    }
    [
        "/opt/homebrew/bin/mpv",
        "/usr/local/bin/mpv",
        "/usr/bin/mpv",
    ]
    .into_iter()
    .find(|p| std::path::Path::new(p).exists())
    .unwrap_or("mpv")
    .to_string()
}

fn resolve_mpv_absolute() -> String {
    let resolved = resolve_mpv();
    if std::path::Path::new(&resolved).is_absolute() {
        return resolved;
    }
    find_on_path(&resolved).unwrap_or(resolved)
}

pub fn helper_status() -> serde_json::Value {
    let mpv = resolve_mpv_absolute();
    let webtorrent = resolve_webtorrent();
    serde_json::json!({
        "mpv": {
            "available": std::path::Path::new(&mpv).is_absolute() || command_exists(&mpv),
            "path": mpv,
        },
        "webtorrent": {
            "available": webtorrent.is_some(),
            "path": webtorrent,
        },
    })
}

fn find_on_path(program: &str) -> Option<String> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|dir| dir.join(program))
        .find(|candidate| candidate.is_file())
        .map(|p| p.to_string_lossy().into_owned())
}

fn child_path() -> String {
    let current = std::env::var("PATH").unwrap_or_default();
    if cfg!(target_os = "macos") {
        let profile_bin = crate::settings::profile_dir().join("node_modules/.bin");
        format!(
            "{}:/opt/homebrew/bin:/usr/local/bin:{current}",
            profile_bin.display()
        )
    } else {
        current
    }
}

fn torrent_child_path(home: &Path) -> String {
    format!("{}:{}", home.join("bin").display(), child_path())
}

fn stop(player: &mut Option<Child>) {
    if let Some(mut old) = player.take() {
        kill_tree(&mut old);
    }
}

fn command_exists(program: &str) -> bool {
    Command::new(program)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok()
}

pub fn spawn_detached(program: &str, args: &[&str]) -> std::io::Result<()> {
    spawn_detached_env(program, args, &[])
}

pub fn spawn_detached_env(
    program: &str,
    args: &[&str],
    envs: &[(&str, &str)],
) -> std::io::Result<()> {
    Command::new(program)
        .args(args)
        .envs(envs.iter().copied())
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map(drop)
}

/// Like [`spawn_detached_env`] but, in the TV/gamescope session, wraps the
/// launch in `gamescope [profile args] -- <program> <args>` so games and
/// emulators render into the compositor's fullscreen output. Off-session (or
/// when gamescope isn't on PATH) it degrades to a plain detached launch, so
/// desktop/app mode is unchanged. Game launch sites (epic/steam/retro) should
/// prefer this over `spawn_detached` for a consistent 10-foot experience.
pub fn spawn_detached_game(
    program: &str,
    args: &[&str],
    envs: &[(&str, &str)],
) -> std::io::Result<()> {
    if let Some(gs) = gamescope_prefix() {
        // Run gamescope as the program; its profile args, then `--`, then the
        // real command follow. gs[0] is "gamescope".
        let mut gs_args: Vec<&str> = gs[1..].iter().map(String::as_str).collect();
        gs_args.push("--");
        gs_args.push(program);
        gs_args.extend_from_slice(args);
        return spawn_detached_env(&gs[0], &gs_args, envs);
    }
    spawn_detached_env(program, args, envs)
}

/// True when running inside the TV session where every launch should go through
/// gamescope (per PLAN.md). Gated by env so desktop/app mode never wraps.
fn in_tv_session() -> bool {
    matches!(std::env::var("TVOS_GAMESCOPE").as_deref(), Ok("1"))
        || matches!(std::env::var("TVOS_TV").as_deref(), Ok("1"))
}

/// The `gamescope [profile args]` prefix to run a launch under, or None when
/// not in the TV session or gamescope isn't installed (→ direct launch).
/// TVOS_GAMESCOPE_ARGS overrides the conservative default profile.
fn gamescope_prefix() -> Option<Vec<String>> {
    if !in_tv_session() || !command_exists("gamescope") {
        return None;
    }
    let mut prefix = vec!["gamescope".to_string()];
    match std::env::var("TVOS_GAMESCOPE_ARGS") {
        Ok(args) if !args.trim().is_empty() => {
            prefix.extend(args.split_whitespace().map(String::from));
        }
        // Conservative default: fullscreen, HDR left to gamescope's own detection.
        _ => prefix.push("-f".to_string()),
    }
    Some(prefix)
}

/// A [`Command`] for `program`, transparently wrapped in gamescope when in the
/// TV session (and gamescope is present). Callers set env/args/stdio as usual.
fn gamescope_command(program: &str) -> Command {
    match gamescope_prefix() {
        Some(prefix) => {
            let mut cmd = Command::new(&prefix[0]);
            cmd.args(&prefix[1..]).arg("--").arg(program);
            cmd
        }
        None => Command::new(program),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::upscale::Profile;

    #[test]
    fn provisions_player_and_writes_conf() {
        let dir = std::env::temp_dir().join(format!("tvos-mpvhome-{}", std::process::id()));
        std::env::set_var("TVOS_MPV_HOME", &dir);
        let profile = Profile {
            name: "test".into(),
            args: vec![
                "--profile=high-quality".into(),
                "--glsl-shaders=/a.glsl:/b.glsl".into(),
            ],
        };
        prepare_mpv_home(
            &profile,
            EnhanceMode::Off,
            "Movie.1080p.mkv",
            None,
            Some(&PlayerMeta::new("Movie \"Night\"\nFinale")),
            false,
        );

        let conf = std::fs::read_to_string(dir.join("mpv.conf")).unwrap();
        assert!(conf.contains("fullscreen=yes"));
        assert!(conf.contains("osc=no")); // TV OS is the UI
        assert!(conf.contains("load-scripts=no"));
        assert!(conf.contains("tvos_player.lua"));
        assert!(conf.contains("thumbfast.lua"));
        assert!(conf.contains("force-media-title=\"Movie Night Finale\""));
        assert!(conf.contains("input-gamepad=yes")); // controller support
        assert!(conf.contains("glsl-shaders=\"/a.glsl:/b.glsl\""));

        // The bundled TV overlay and its thumbnail helper are installed.
        assert!(dir.join("scripts/tvos_player.lua").exists());
        assert!(dir.join("scripts/thumbfast.lua").exists());
        assert!(dir.join("scripts/upscaler.lua").exists());
        assert!(dir.join("scripts/controller.lua").exists());
        assert!(dir.join("bin/mpv").exists());
        assert!(dir.join("input.conf").exists());
        // The legacy ModernZ OSC is gone — tvos_player.lua is the sole UI.
        assert!(!dir.join("scripts/modernz.lua").exists());

        // The upscaler menu has its preset list, with a valid active preset.
        let upscalers = std::fs::read_to_string(dir.join("upscalers.json")).unwrap();
        assert!(upscalers.contains("\"active\":\"Off\""));
        assert!(upscalers.contains("\"presets\""));

        std::env::remove_var("TVOS_MPV_HOME");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
