//! Process helpers for launching content.
//!
//! Video plays in mpv, but configured to look and behave like a real player:
//! we point mpv at a private config dir (MPV_HOME) that carries the uosc UI +
//! thumbfast thumbnails (installed by system/get-player.sh) and a freshly
//! written mpv.conf holding the resolved Enhance shader chain. Because the
//! config travels via MPV_HOME, *every* mpv launch picks it up — including the
//! one webtorrent-cli spawns for torrents — so torrents get the same player
//! and upscaler, with seeking, via webtorrent's built-in HTTP server.

use std::path::PathBuf;
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;

use crate::upscale::Profile;

/// The currently playing player process, if any. Starting a new video stops
/// the previous one so two windows never fight over the screen.
static PLAYER: Mutex<Option<Child>> = Mutex::new(None);

/// Base mpv settings for the 10-foot player: fullscreen, good streaming cache,
/// sensible subtitle/audio defaults. UI (osc/uosc) and the Enhance shaders are
/// appended per-playback.
const BASE_MPV_CONF: &str = "\
# Generated by tvosd on each playback — do not edit.
fullscreen=yes
border=no
terminal=no
force-window=immediate
keep-open=yes
hwdec=auto-safe
profile=high-quality
slang=en,eng
alang=en,eng
sub-auto=fuzzy
sub-font-size=42
volume=100
volume-max=130
# Smooth streaming of remote sources.
cache=yes
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=64MiB
demuxer-readahead-secs=30
network-timeout=60
ytdl-format=bestvideo[height<=?2160]+bestaudio/best
";

pub fn play_video(target: &str, profile: &Profile) -> Result<(), String> {
    let home = prepare_mpv_home(profile);
    let mut player = PLAYER.lock().unwrap();
    stop(&mut player);

    println!("playing [{}] {target}", profile.name);
    let child = Command::new("mpv")
        .env("MPV_HOME", &home)
        .args(["--no-terminal", target])
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(play_log(&home))
        .spawn()
        .map_err(|e| format!("could not start mpv: {e}"))?;
    *player = Some(child);
    Ok(())
}

/// Opens a link (a WatchHub service, an addon's /configure page) in the
/// system's default handler — the browser, or the streaming service's app.
pub fn open_external(url: &str) -> Result<(), String> {
    let opener = if cfg!(target_os = "macos") {
        "open"
    } else {
        "xdg-open"
    };
    spawn_detached(opener, &[url]).map_err(|e| format!("could not open link: {e}"))
}

/// Streams a torrent magnet in mpv (with the upscaler + UI) via webtorrent-cli's
/// `--mpv` mode, which serves the torrent over local HTTP so seeking works.
pub fn play_torrent(magnet: &str, file_idx: Option<i64>, profile: &Profile) -> Result<(), String> {
    let webtorrent = resolve_webtorrent().ok_or(
        "Torrent playback needs webtorrent-cli. Install it with `npm install -g webtorrent-cli`, \
         or configure the addon with a debrid service (e.g. RealDebrid) for direct streams.",
    )?;
    let home = prepare_mpv_home(profile);
    let mut player = PLAYER.lock().unwrap();
    stop(&mut player);

    // Download to a predictable, disk-backed cache dir. webtorrent otherwise
    // writes to the working dir or /tmp (often a small tmpfs), which fills up
    // fast on big torrents — a common cause of "no space" failures.
    let cache = torrent_cache();
    let _ = std::fs::create_dir_all(&cache);

    // `webtorrent <magnet> --mpv` (download is the default command). With a
    // file index, --select streams that file; without it webtorrent picks the
    // largest playable file automatically.
    let mut cmd = Command::new(&webtorrent);
    cmd.arg(magnet).arg("--mpv").arg("--out").arg(&cache);
    if let Some(i) = file_idx {
        cmd.args(["--select", &i.to_string()]);
    }
    // webtorrent spawns mpv; MPV_HOME makes that mpv use our UI + shaders.
    println!("playing [torrent {}] via {webtorrent}", profile.name);
    let child = cmd
        .env("MPV_HOME", &home)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(play_log(&home))
        .spawn()
        .map_err(|e| format!("could not start torrent stream: {e}"))?;
    *player = Some(child);
    Ok(())
}

/// Writes mpv.conf for this playback into our MPV_HOME and returns it. Keeps
/// the always-on Enhance A/B toggle script in place; uses uosc if installed
/// (get-player.sh), else mpv's built-in OSC so there's always a seek bar.
fn prepare_mpv_home(profile: &Profile) -> PathBuf {
    let home = mpv_home();
    let scripts = home.join("scripts");
    let _ = std::fs::create_dir_all(&scripts);
    let _ = std::fs::write(
        scripts.join("enhance-toggle.lua"),
        include_str!("../data/enhance-toggle.lua"),
    );

    let has_uosc = scripts.join("uosc/main.lua").exists();
    let mut conf = String::from(BASE_MPV_CONF);
    conf.push_str(if has_uosc { "osc=no\n" } else { "osc=yes\n" });
    // A real log file (mpv writes nothing to a suppressed terminal) so the
    // actual reason a stream fails is always visible.
    conf.push_str(&format!(
        "log-file=\"{}\"\n",
        home.join("mpv.log").display()
    ));
    // Turn the resolved profile's "--key=value" mpv flags into config lines so
    // they apply to webtorrent's mpv too (which we can't pass args to).
    for arg in &profile.args {
        if let Some((key, value)) = arg.trim_start_matches("--").split_once('=') {
            conf.push_str(&format!("{key}=\"{value}\"\n"));
        }
    }
    let _ = std::fs::write(home.join("mpv.conf"), conf);
    home
}

fn mpv_home() -> PathBuf {
    if let Ok(dir) = std::env::var("TVOS_MPV_HOME") {
        return PathBuf::from(dir);
    }
    PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".local/share/tvos/mpv")
}

/// Where webtorrent downloads torrent data (disk-backed, easy to clear).
fn torrent_cache() -> PathBuf {
    if let Ok(dir) = std::env::var("TVOS_TORRENT_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".cache/tvos/torrents")
}

/// Truncates and opens the per-playback log (player stderr) for diagnosis.
fn play_log(home: &std::path::Path) -> Stdio {
    std::fs::File::create(home.join("play.log"))
        .map(Stdio::from)
        .unwrap_or_else(|_| Stdio::null())
}

/// Finds the webtorrent binary on PATH, or in the usual npm-global locations
/// (a desktop-launched daemon often has a minimal PATH that misses them).
fn resolve_webtorrent() -> Option<String> {
    if command_exists("webtorrent") {
        return Some("webtorrent".to_string());
    }
    let home = std::env::var("HOME").unwrap_or_default();
    let mut candidates = vec![
        format!("{home}/.npm-global/bin/webtorrent"),
        format!("{home}/.local/bin/webtorrent"),
        format!("{home}/node_modules/.bin/webtorrent"),
        "/usr/local/bin/webtorrent".to_string(),
        "/usr/bin/webtorrent".to_string(),
    ];
    // `npm prefix -g`/bin is where `npm install -g` puts binaries.
    if let Ok(out) = Command::new("npm").args(["prefix", "-g"]).output() {
        if out.status.success() {
            let prefix = String::from_utf8_lossy(&out.stdout).trim().to_string();
            candidates.push(format!("{prefix}/bin/webtorrent"));
        }
    }
    candidates
        .into_iter()
        .find(|p| std::path::Path::new(p).exists())
}

fn stop(player: &mut Option<Child>) {
    if let Some(mut old) = player.take() {
        let _ = old.kill();
        let _ = old.wait();
    }
}

fn command_exists(program: &str) -> bool {
    Command::new(program)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok()
}

pub fn spawn_detached(program: &str, args: &[&str]) -> std::io::Result<()> {
    spawn_detached_env(program, args, &[])
}

pub fn spawn_detached_env(
    program: &str,
    args: &[&str],
    envs: &[(&str, &str)],
) -> std::io::Result<()> {
    Command::new(program)
        .args(args)
        .envs(envs.iter().copied())
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map(drop)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::upscale::Profile;

    #[test]
    fn mpv_conf_has_ui_and_shaders() {
        let dir = std::env::temp_dir().join(format!("tvos-mpvhome-{}", std::process::id()));
        std::env::set_var("TVOS_MPV_HOME", &dir);
        let profile = Profile {
            name: "test".into(),
            args: vec![
                "--profile=high-quality".into(),
                "--glsl-shaders=/a.glsl:/b.glsl".into(),
            ],
        };
        prepare_mpv_home(&profile);
        let conf = std::fs::read_to_string(dir.join("mpv.conf")).unwrap();
        assert!(conf.contains("fullscreen=yes"));
        assert!(conf.contains("osc=")); // a seek bar is always configured
        assert!(conf.contains("glsl-shaders=\"/a.glsl:/b.glsl\""));
        assert!(dir.join("scripts/enhance-toggle.lua").exists());
        std::env::remove_var("TVOS_MPV_HOME");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
